"use client";

import UserLayout from "@/components/layout/UserLayout";
import "@/styles/globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import store from "@/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>
          <UserLayout>{children}</UserLayout>
        </body>
      </Provider>
    </html>
  );
}
