"use client";

import UserLayout from "@/components/layout/UserLayout";
import "@/styles/globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from "react-redux";
import store from "@/store";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "react-multi-carousel/lib/styles.css";
import "react-date-range/dist/styles.css";
import "react-date-range/dist/theme/default.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider store={store}>
        <body className={inter.className}>
          <UserLayout>{children}</UserLayout>
          <ToastContainer />
        </body>
      </Provider>
    </html>
  );
}
